[package]
name = "vortek"
version = "0.1.0"
authors = ["Lars Frogner <lars_frogner@hotmail.com>"]
edition = "2018"

[features]
default = []
gl = []

[dependencies]
wgpu =  "0.4"
log = "0.4.8"
simple_logger = "1.4.0"
arrayvec = "0.5.1"
